"""Prepare the shared UE4SS CMake package used by every native mod."""
import argparse
import json
import os
from pathlib import Path
import re
import subprocess
import xml.etree.ElementTree as ET

from palmods import ROOT, UE4SS_BUILD, UE4SS_SOURCE

CONFIGURATION = 'Game__Shipping__Win64'


def toolset_environment(toolset):
    env = os.environ.copy()
    version = re.search(r'(?:^|,)version=([^,]+)', toolset or '')
    if version:
        # CMake compiler detection can otherwise use MSBuild's default toolset.
        env['VCToolsVersion'] = version.group(1)
    return env


def quoted(value):
    value = str(value).replace('\\', '/')
    if ']=]' in value:
        raise ValueError('Unsupported CMake bracket delimiter in SDK value')
    return '[=[' + value + ']=]'


def export_package(project, cache_root, source_root, destination, old_root=None, toolset=None):
    project, cache_root, source_root = map(lambda p: Path(p).resolve(), (project, cache_root, source_root))
    ns = {'m': 'http://schemas.microsoft.com/developer/msbuild/2003'}
    xml = ET.parse(project)
    group = next((g for g in xml.findall('m:ItemDefinitionGroup', ns)
                  if f'{CONFIGURATION}|x64' in g.get('Condition', '')), None)
    if group is None:
        raise ValueError(f'Missing {CONFIGURATION}|x64 settings in {project}')

    def values(field):
        return [v for v in (group.findtext(field, default='', namespaces=ns)).split(';')
                if v and not v.startswith('%(')]

    def relocate(value):
        normalized = value.replace('\\', '/')
        if old_root:
            prefix = str(old_root).replace('\\', '/').rstrip('/') + '/'
            if normalized.lower().startswith(prefix.lower()):
                suffix = normalized[len(prefix):]
                if suffix.startswith('RE-UE4SS/'):
                    return (source_root / suffix[len('RE-UE4SS/'):]).as_posix()
                if suffix.startswith('build/'):
                    return (cache_root / suffix[len('build/'):]).as_posix()
                return None  # Former consumer's private includes are not SDK requirements.
        return normalized

    includes = values('m:ClCompile/m:AdditionalIncludeDirectories')
    options = group.findtext('m:ClCompile/m:AdditionalOptions', default='', namespaces=ns)
    includes.extend(re.findall(r'/external:I\s+"([^"]+)"', options))
    includes = [relocate(p) for p in includes]
    includes = list(dict.fromkeys(p for p in includes if p and Path(p).is_dir()
                                 and Path(p).resolve() != project.parent))
    definitions = [d for d in values('m:ClCompile/m:PreprocessorDefinitions')
                   if not d.endswith('_EXPORTS') and not d.startswith('CMAKE_INTDIR=')]
    libraries = []
    for lib in values('m:Link/m:AdditionalDependencies'):
        relocated = relocate(lib)
        if relocated is None:
            raise ValueError(f'Cannot relocate SDK library: {lib}')
        if '/' in relocated or '\\' in relocated:
            path = (project.parent / relocated).resolve()
            if not path.is_file():
                raise FileNotFoundError(f'Missing SDK library: {path}')
            libraries.append(path.as_posix())
        else:
            libraries.append(relocated)
    if not any(Path(lib).name.lower() == 'ue4ss.lib' for lib in libraries):
        raise ValueError('SDK consumer does not link UE4SS.lib')
    if (source_root / 'UE4SS/include').as_posix() not in includes:
        raise ValueError('SDK consumer is missing UE4SS headers')
    # Only publish after the complete set of referenced libraries is present.
    destination = Path(destination)
    destination.mkdir(parents=True, exist_ok=True)
    config = ['# Generated by tools/build_sdk.py; shared Shipping SDK only.',
              'if(NOT TARGET PalMods::UE4SS)',
              '  add_library(PalMods::UE4SS INTERFACE IMPORTED)',
              '  set_property(TARGET PalMods::UE4SS PROPERTY INTERFACE_INCLUDE_DIRECTORIES '
              + ' '.join(quoted(p) for p in includes) + ')',
              '  set_property(TARGET PalMods::UE4SS PROPERTY INTERFACE_COMPILE_DEFINITIONS '
              + ' '.join(quoted(d) for d in definitions) + ')',
              '  set_property(TARGET PalMods::UE4SS PROPERTY INTERFACE_LINK_LIBRARIES '
              + ' '.join(quoted(lib) for lib in libraries) + ')',
              '  set_property(TARGET PalMods::UE4SS PROPERTY INTERFACE_COMPILE_FEATURES cxx_std_20)',
              'endif()']
    (destination / 'PalModsSDKConfig.cmake').write_text('\n'.join(config) + '\n', encoding='utf-8')
    manifest = dict(configuration=CONFIGURATION, source=str(source_root), project=str(project),
                    origin='legacy-import' if old_root else 'shared-build', toolset=toolset,
                    includes=includes, libraries=libraries)
    (destination / 'sdk.json').write_text(json.dumps(manifest, indent=2), encoding='utf-8')


def ensure_sdk(parallel=4, toolset=None, rebuild=False):
    manifest = UE4SS_BUILD / 'sdk.json'
    if not rebuild and manifest.is_file() and (UE4SS_BUILD / 'PalModsSDKConfig.cmake').is_file():
        info = json.loads(manifest.read_text(encoding='utf-8'))
        if toolset and info['toolset'] != toolset:
            raise ValueError(f'Shared SDK toolset is {info["toolset"]!r}, requested {toolset!r}; use --rebuild-sdk')
        if Path(info['source']).resolve() != UE4SS_SOURCE:
            raise ValueError('Shared SDK source changed; use --rebuild-sdk')
        for lib in info['libraries']:
            if '/' in lib and not Path(lib).is_file():
                raise FileNotFoundError(f'Missing shared SDK library: {lib}; use --rebuild-sdk')
        print(f'Using shared UE4SS SDK: {UE4SS_BUILD} ({info["origin"]})', flush=True)
        return info['toolset']
    configure = ['cmake', '-S', str(ROOT / 'tools/sdk'), '-B', str(UE4SS_BUILD),
                 '-G', 'Visual Studio 17 2022', '-A', 'x64', '-DUE4SS_SOURCE=' + str(UE4SS_SOURCE)]
    if toolset:
        configure.extend(['-T', toolset])
    env = toolset_environment(toolset)
    subprocess.run(configure, cwd=ROOT, env=env, check=True)
    command = ['cmake', '--build', str(UE4SS_BUILD), '--config', CONFIGURATION,
               '--target', 'PalModsSDKProbe', '--parallel', str(parallel)]
    version = re.search(r'(?:^|,)version=([^,]+)', toolset or '')
    if version:
        command.extend(['--', '/p:VCToolsVersion=' + version.group(1)])
    subprocess.run(command, cwd=ROOT, env=env, check=True)
    export_package(UE4SS_BUILD / 'PalModsSDKProbe.vcxproj', UE4SS_BUILD, UE4SS_SOURCE,
                   UE4SS_BUILD, toolset=toolset)
    return toolset


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--import-project', type=Path, required=True, help='One-time import of an existing SDK consumer vcxproj')
    parser.add_argument('--cache-root', type=Path, required=True)
    parser.add_argument('--old-root', required=True, help='Original source root encoded in that project')
    parser.add_argument('--toolset', required=True, help='Toolset matching the cached SDK libraries')
    args = parser.parse_args()
    export_package(args.import_project, args.cache_root, UE4SS_SOURCE, UE4SS_BUILD,
                   old_root=args.old_root, toolset=args.toolset)
    print(f'Imported shared SDK package: {UE4SS_BUILD}; historical libraries still required.')


if __name__ == '__main__':
    main()
